const Movie = require('./models/movie');

require('dotenv').config();
require('./config/database');

Movie.remove({})
    .then(function () {
        return Movie.create([
            {
                "title": "Birdman",
                "genre": "Comedy, Drama",
                "year": 2014, "runtime": "1h 59min", "rating": "R",
                "synopsis": "A washed-up actor, who once played an iconic superhero, attempts to revive his career by writing and starring in his very own Broadway play.",
                "psychologist": "Timothy Yen, Psy. D., Licensed Clinical Psychologist",
                "recommend": "This movie can help you to self-evaluate your condition, or build awareness about your mental condition, improve your thinking quality? by reflecting on the movie's character you can identify the difference between positive and negative influence of narratives in your head. You can witness how sometimes actions and human behavior is driven by obsessive thoughts, dysfunctional beliefs, that could lead to a tragedy. It is important to learn when is the critical point to ask for help, especially if you are dealing with depression, anxiety and movie Birdman can show you an example of that. “Birdman” is an artistic and thematically ambiguous film about a dwindled American actor Riggan Thomson, famous for his role as a superhero “Birdman” 20 years ago, who is trying his luck of breaking out of his mid-life crisis and getting back into the public eye as a successful actor. The characters in the movie express the thoughts and feelings of the human struggles, such as self-doubt (e.g., 'Can I really do this ? ', resentment (e.g, 'I hate the actor that has been assigned to this play against my choice'), and disappointment (e.g., My daughter has really let me down because I know she could do better').The main character's condition and behavior is influenced by life stressors, his strained relationship with his recovering drug addicted daughter, the reappearance of his ex-wife, a theater critic bent on destroying his reputation, and a replacement co-actor who does questionable things in the name of “art”. One of the most interesting dynamics in the movie is his visual and auditory hallucination of Birdman who tries to convince him to quit the play and other critical comments, that eventually leads him to commit suicide.",
                "learn": "There are multiple mental health themes in this movie to include drug addiction, psychotic symptoms (like Schizophrenia), and suicide. It is important to be aware of these symptoms and to identify your mental and emotional limits. One important aspect of self-discovery is to listen to the type of narratives in your head. Are they overly critical? Is there primarily negativity or hopelessness? What emotions are attached to these thoughts? In either case, taking the time to distinguish whether these voices are positive or negative influences will dictate the course of treatment in needing help or not. If these voices or inner dialogue is going against your values on a healthy life, then you are not alone and need help. In the movie, Riggan does not deal with these voices in a healthy way. First of all, he does not tell anyone about them for fear of judgment. Then he lashes out in angry outbursts and uses alcohol as a way to manage his emotions. These kind of destructive behaviors are also signs that things are not being managed as well as they can be. A healthier way to deal with these issues is to be honest with oneself about one’s thoughts and feelings no matter how negative they may be. If you have a trusted other person to confide in, that would be a good time to connect with other people. There are other coping skills that can help decrease stress such as mindfulness skills and deep breathing as well. In this film, suicide is somewhat glorified but the reality is that it is not the solution to anyone’s problems so awareness of that false theme is important. What is not completely clear is whether the hallucinations is the result of a mental disorder or an overactive imagination. The information obtained during self-discovery would tremendously help during the session with a therapist.",
                "warning": "The movie is rated R for some of these more gritty and dark themes. This may be triggering for people who have experienced sexual or physical abuse as well as depression especially with suicidal thoughts. There are some disturbing scenes with the overly artistic colleague Mike who tries to attempt sex with the other actress as well as the suicide scene at the end where he actually takes a gun to shoot himself in the head. This may also be triggering for people who are recovering from alcohol addiction as there is a scene where Riggan relapses at a bar. If you have any concerns about the health of watching this film, please consult your counselor.",
                "image": "https://i.imgur.com/d0SuuF9.jpg",
                "levelOne": "true"
            },
            {
                "title": "Moonlight",
                "genre": "Drama",
                "year": 2016, "runtime": "1h 51min", "rarting": "R",
                "synopsis": "A chronicle of the childhood, adolescence and burgeoning adulthood of a young, African-American, gay man growing up in a rough neighborhood of Miami.",
                "psychologist": "Timothy Yen, Psy. D., Licensed Clinical Psychologist",
                "recommend": "“Moonlight” is a powerful movie about identity. What makes up a person’s identity? Motivational speaker Jim Rohn has been quoted that “you’re the average of the five people you spend the most time with.” Follow the life of Chiron and identify the relationships that have shaped him to become the man he is at the end of the movie. See if you can distinguish the healthy influences from the unhealthy influences. There is an ongoing debate between nature (biological factors like genes) vs. nurture (environmental/relational factors) playing a significant role in shaping our lives. This draws out the question “who is the authentic Chiron?” Navigate both nature and nurture factors that have contributed to his identity.",
                "learn": "Realize that the relationships in our lives can play a powerful role in who we are today both healthy and unhealthy. This can help us realize the origins of our beliefs and behaviors in hopes that we can become more conscious and intentional about choosing how we identify ourselves now. Instead of automatically accepting ourselves for what we are, taking the time to sort out our identity and create who you want to become with the help of wise counsel and Inlite Cinema Therapist.",
                "warning": "This movie has some difficult scenes of neglect and child abuse that may be triggering for people who have experienced similar things. There is also a scene where two teenage boys are implying sexual activity which may be uncomfortable for some viewers to watch due to cultural or spiritual beliefs. It is a more dark and gritty kind of movie so it may be advised to watch this movie under therapist guidance as needed.",
                "image": "https://i.imgur.com/ZmW67L2.jpg",
                "levelOne": "true",
                "levelTwo": "true"
            },
            {
                "title": "Her",
                "genre": "Drama, Romance",
                "year": 2013, "runtime": "2h 6min", "rating": "R",
                "synopsis": "In a near future, a lonely writer develops an unlikely relationship with an operating system designed to meet his every need.",
                "psychologist": "Timothy Yen, Psy. D., Licensed Clinical Psychologist",
                "recommend": "“Her” is a timely movie that addresses our human need for relationships and our different kind of needs. In our 21st century time, communication and relationships are more and more commonly occurring through social media and online platforms. Do online relationships fulfill the same relational needs as in-person relationships? Notice the benefits that Theodore receives from his online relationship with the OS Samantha as well as the drawbacks. Observe the benefits and challenges that Theodore faces with “real” in-person relationships. One example of a benefit is that the OS Samantha is always available and always empathetic as a listening ear for Theodore. On the other hand, he is unable to physically hold her or see her like in a real person relationship with Amy.",
                "learn": "This movie can help you evaluate the values and costs of your current and potential relationships. Like all relationships, there are benefits and costs as well to consider with different levels of intimacy depending on factors such as commitment level, openness, common interest, etc. The film also raises the question about realistic expectations as well as selfish vs. selfless pursuits. You can assess which kind of relationships are healthy and worth maintaining while knowing which ones are better left alone.",
                "warning": "This movie is rated R for some sexual content so do not watch it if these scenes make you feel uneasy. Otherwise the movie addresses someone with depressive symptoms and social skill challenges but unlikely to be triggering. Please consult your online therapist and watch with guidance.",
                "image": "https://i.imgur.com/xHfiY6h.jpg",
                "levelOne": "true",
                "levelTwo": "true",
                "levelThree": "true"
            },
            {
                "title": "The Big Sick",
                "genre": "Comedy, Drama, Romance",
                "year": 2017, "runtime": "2h", "rating": "R",
                "synopsis": "Pakistan-born comedian Kumail Nanjiani and grad student Emily Gardner fall in love but struggle as their cultures clash. When Emily contracts a mysterious illness, Kumail finds himself forced to face her feisty parents, his family's expectations, and his true feelings.",
                "psychologist": "Dr. Joy Jacobs J.D., Ph.D., Clinical Psychologist",
                "recommend": "The Big Sick explores important themes of acculturation and assimilation. The main character Kumail (a first generation American whose family is from Pakistan) struggles to reconcile his own interests and passions with those of his culturally traditional family. Attracted to American girls, instead of the arranged marriage his parents expect him to agree to, and drawn to standup comedy (instead of a more traditionally accepted career like law or medicine), Kumail becomes avoidant and deceptive to cope. Kumail hides his American girlfriend from his parents and his passion for standup comedy. He struggles with the stress and confusion of living what amounts to a double life. Like many young men, Kumail struggles with his fears of commitment and the dissonance between his family's desires for him and his own. His inability to live in and own his truth creates severe ruptures in his relationships--family and romantic. Kumail is forced to face the demons he has been running away from when his ex-girlfriend Emily lies in a coma in the hospital. For the first time, he is able to recognize the love he feels for another and to sacrifice his own goals for the needs of another. This awakening opens Kumail's heart and allows him to confront the many issues he has tried to avoid for so long. By facing the dissonance between his feelings and his behavior, he is able to finally identify and stand up for his own desires.",
                "learn": "In the movie, Riggan does not deal with these voices in a healthy way. First of all, he does not tell anyone about them for fear of judgment. Then he lashes out in angry outbursts and uses alcohol as a way to manage his emotions. These kind of destructive behaviors are also signs that things are not being managed as well as they can be. A healthier way to deal with these issues is to be honest with oneself about one’s thoughts and feelings no matter how negative they may be. If you have a trusted other person to confide in, that would be a good time to connect with other people. There are other coping skills that can help decrease stress such as mindfulness skills and deep breathing as well. In this film, suicide is somewhat glorified but the reality is that it is not the solution to anyone’s problems so awareness of that false theme is important. What is not completely clear is whether the hallucinations is the result of a mental disorder or an overactive imagination. The information obtained during self-discovery would tremendously help during the session with a therapist",
                "warning": "Throughout the movie, various characters engage in excessive alcohol intake and decide to “stress eat” together. These themes are treated lightly in the movie, but could be triggering to someone actively struggling with alcohol addiction or eating disorders.",
                "image": "https://i.imgur.com/HwNj0Cw.jpg",
                "levelOne": "true",
                "levelTwo": "true",
                "levelThree": "true"
            },
            {
                "title": "Manchester by the Sea",
                "genre": "Drama",
                "year": 2016, "runtime": "2h 17min", "rating": "R",
                "synopsis": "A depressed uncle is asked to take care of his teenage nephew after the boy's father dies.",
                "psychologist": "Timothy Yen, Psy. D., Licensed Clinical Psychologist",
                "recommend": "Manchester by the Sea is a powerful and rich movie that talks about painful loss in family relationships and how different people deal (or not deal) with these challenges. Notice the different kinds of loss and challenges in different dyadic relationships between husbands and wives, parents and children, and between friends. Notice what happens when trauma and guilt occur and the devastation it can cause for the individual and those around a person especially when it is not dealt with in a healthy manner. Also notice the powerful redemptive characters in the movie that help bring some of these hurting characters back into a more restorative relationship. Some mental health issues that arise from this movie include depression, Post-Traumatic Stress Disorder (PTSD), anxiety, and substance abuse as a result of unhealthy coping with life’s challenges. Begin by identifying emotionally safe people to talk with and get support. Also seek out a therapist and grief groups for safe people to come along one’s journey. Identify life giving activities and coping skills to help work through difficult feelings. Challenges in communication with significant others may benefit from couples therapy and groups.",
                "learn": "In many ways, this movie is more of a guide in “what not to do” rather than what to emulate. Hopefully these masterfully interwoven stories can bring awareness to some ruptures or losses in your relationship as well as realize any guilt or shame that has not been properly dealt with and begin a dialogue of what to do to begin the journey of a restorative relationship.",
                "warning": "This movie is rated R primarily for the numerous bad words and cursing so if that is a trigger for your mental health concerns, this may not be the best movie. People suffering from PTSD especially if the stressors are tied in to a death of one’s child. I believe people suffering from depression and anxiety in a moderate to mild level should be okay though having a therapist guide them through any difficult thoughts and emotions is generally recommended.",
                "image": "https://i.imgur.com/2UGUuxi.jpg",
                "levelOne": "true"
            },
            {
                "title": "Frances Ha",
                "genre": "Comedy, Drama, Romance",
                "year": 2012, "runtime": "1h 26min", "rating": "R",
                "synopsis": "A story that follows as a New York woman (who doesn't really have an apartment) apprentices for a dance company (though she's not really a dancer) and throws herself headlong into her dreams, even as their possibility dwindles.",
                "psychologist": "Dr. Joy Jacobs J.D., Ph.D., Clinical Psychologist",
                "recommend": "Frances Ha is a poignant coming of age film. Throughout the course of this film, we see Frances progress from a state of insecurity, social anxiety, and alienation to a place of proudly owning her own space in the world. Initially, Frances struggles tremendously with dating, female friendships and her career as dancer. She seems hopeless awkward. Nothing seems to work out for Frances and she starts to fear that she will amount to nothing. This turns out to be the place of true transformation in France's life. For Frances, hitting 'bottom' emotionally is an important step toward her birth as a strong, creative individual who becomes comfortable in her own skin. Watching Frances's path of transformation will be tremendously helpful to anyone facing similar challenges.",
                "learn": "Frances Ha tracks the inspiring growth and transformation of an individual from a state dis-ease, depression and anxiety to one of confidence and joy. Frances's transformation as a person provides a trajectory for healing for anyone struggling to define who they are and how they fit into the outside world. The path is not always easy; Frances takes many bumps and bruises along the way. Her ultimate triumph is instructive of the notion that nothing is truly good or bad--we have the power to interpret our experiences and to make choices that fuel our own growth",
                "warning": "The characters in this movie drink copious amounts of alcohol. This could be triggering to someone struggling with alcoholism. Also, extremely depressed, suggestible, or suicidal viewers should not watch this movie, as the movie does include a veiled suicide attemp.",
                "image": "https://i.imgur.com/GpCNckL.jpg",
                "levelOne": "true",
                "levelTwo": "true"
            },
            {
                "title": "Burnt",
                "genre": "Comedy, Drama",
                "year": 2015, "runtime": "1h 41min", "rating": "R",
                "synopsis": "Adam Jones is a chef who destroyed his career with drugs and diva behavior. He cleans up and returns to London, determined to redeem himself by spearheading a top restaurant that can gain three Michelin stars.",
                "psychologist": "Dr. Joy Jacobs J.D., Ph.D., Clinical Psychologist",
                "recommend": "If you have ever struggled with addiction or know someone who has, Burnt is a must see. This movie provides a vivid treatment of the personality traits that contribute to addiction and can interfere with recovery, as well as providing an inspirational glimpse on how these same traits can be molded to promote and maintain recovery.  Burnt is an attention grabbing and suspense filled movie that captures a chef's healing journey from accomplishment and glory to destruction and ultimately to a triumphant return as a master at his craft. Adam, the central character of the movie, is at the peak of his career when addiction destroys his life and he loses everything. We watch Adam as he struggles to get his life back together--forcing him to leave the gloried kitchens of Europe to shucking oysters in bar in New Orleans as part of his self prescribed healing. After he has shucked his millionth oyster, Adam makes his way back to Europe to resurrect his career and endeavors to earn his third Michelin star. Recovery from any addiction can be a roller coaster. This movie presents the journey of recovery in a realistic and believable manner. In addition, we all experience setbacks of different varieties in life. This movie provides a useful example of one person's journey to the depths and back. If you are feeling isolated or alone in your journey, this movie will instill you with renewed hope that you can bounce back as well.",
                "learn": "Burnt poignantly illustrates the struggles faced in getting clean and sober, the challenges of maintaining sobriety, and the personality challenges that fuel addiction. Adam's perfectionism and stubborn personality, as well as his difficulty managing anger, make him difficult to work with and to love. He struggles in work and personal relationships because his drive for perfection in the kitchen and for his third Michelin star blind him. Unable to manage stress, pressure, and disappointment in the face of payback from a member of his own kitchen staff for past misdeeds, Adam crumbles and seems destined to fall into the throes of addiction once again. This is a critical turning point in the movie, as it ultimately leads Adam to surrender and embark on a path to meaningful recovery. By agreeing to join group therapy for his addiction and willingly engaging with his therapist, Adam ultimately is able to return to the kitchen and experience joy in his craft. He no longer isolates himself from others and finds his creativity again. This ultimately leads him to that coveted third star.",
                "warning": "This movie is an extended treatment of addiction. Anyone triggered by past traumas related to experiences in addiction should be mindful when watching this movie. This movie includes suicidal behaviors; individuals who experience active suicidal ideation should wait to view this film until such thoughts have lifted.",
                "image": "https://i.imgur.com/9C7YmRg.jpg",
                "levelOne": "true"
            },
            {
                "title": "Whiplash",
                "genre": "Drama, Music",
                "year": 2014, "runtime": "1h 47min", "rating": "R",
                "synopsis": "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.",
                "psychologist": "Timothy Yen, Psy. D., Licensed Clinical Psychologist",
                "recommend": " Where do ideas, dreams, and intentions come from? They come from the system of beliefs that we have about our world which shape our expectations. Our beliefs set the frame for our perspectives which led to certain actions. By watching this movie you would be able to see a real example of how our beliefs influence our decisions and actions. It is important to recognize the difference between good intentions and dysfunctional obsessiveness. This requires identifying and setting up healthy boundaries as well as learning the importance of knowing when to let go, setting up achievable expectations, and developing the right attitude towards failure. Try to reflect on the movie and ask yourself “what beliefs are the driving force for your life, where do they come from, what beliefs can put you at risk, and where do you draw your boundaries?” Follow the motives behind both the student Andrew and the conductor Terence who both have great intentions but an unhealthy way of implementation. Andrew Neiman is an aspiring jazz drummer who wants to be the best drummer he can be but at a terrifying cost. What starts off as a privileged invitation from a famous conductor Terence Fletcher to join his studio band, it turns into constant verbal and physical abuse from Terence as he pushes Andrew to be better. Andrew formulates what he believes to be a formula for success. He practices harder than anyone else and spends countless time at the studio. In pursuit of being the best, he believes that having a romantic relationship or any relationship for that manner would deter him from reaching his goals. Andrew sets insanely high expectations and both physically and mentally “beats himself up” for any slight error. This is also heavily influenced and shaped by how Terence treats him which reflects the power of modeling behaviors. Terence also has his version of the “formula of success” which is by giving praise very sparsely but criticizing heavily and acting overly aggressive when the standard is not met. In his mind, this is the only way to bring out “greatness” out of a student but the outcomes of widespread anxiety, irritability, division among the band, and even an act of suicide from a former student seems to speak otherwise.",
                "learn": "One word: boundaries. This movie shows you the essentially what happens when there are a lack of healthy boundaries both personally and interpersonally. There are always costs to pay in pursuing your dreams but this can be accomplished in a healthy way as well as an unhealthy way. Some of the signs that there is a lack of personal boundaries is when a person stops taking care of themselves whether that be eating poorly, choosing to shut loved ones out of one’s life, poor sleeping patterns, and other unhealthy lifestyle changes. Eventually these self-destructive behaviors led to the inability to manage one’s moods (e.g., irritability, anger outbursts, depressed feelings, lack of interest, etc.) and the failure to live according to one’s personal values (e.g., honest with oneself, self-respect, etc.). The sign that there are unhealthy interpersonal boundaries include the inability to say “no” to disrespectful requests, permitting abusive behaviors against oneself, and being pitted against other colleagues in a hateful way in order to prove oneself. A sign of healthy boundaries will demonstrate the opposite characteristics like being able to communicate honestly, have the ability to step back to take care of oneself, being given a certain level of consideration in workload, encouraging words, and other interactions that are life-giving rather than life-sucking. It is good to evaluate your current relationships to identify the condition of the current boundaries and perhaps work with a therapist on re-negotiating unhealthy ones.",
                "warning": "There are triggering scenes of physical and verbal abuse between one in authority and the student. Those who have physical or verbal abuse histories either personally or seeing other people go through abuse, this movie may be too intense to watch. The conductor displays very intense and drastic anger outbursts that lead to throwing chairs, slapping people’s faces, and public humiliation that can be difficult to watch. If you have questions on whether this is a good movie to watch given your personal experiences, please consult your counselor.",
                "image": "https://i.imgur.com/NQmDWGJ.jpg",
                "levelOne": "true",
                "levelTwo": "true"
            },

            {
                "title": "Shame",
                "genre": "Drama",
                "year": 2011, "runtime": "1h 41min", "rating": "NC-17",
                "synopsis": "A man's carefully cultivated private life is disrupted when his sister arrives for an indefinite stay.",
                "psychologist": "Timothy Yen, Psy. D., Licensed Clinical Psychologist",
                "recommend": "This movie would help you to reevaluate your sexual attitude, identify the stages of sexual addiction, evaluate your own experiences with intimacy, and the relational qualities that are most meaningful to you. Also this story may encourage you to get further support from a therapist if you find too much similarities with the main character. “Shame” is a movie that does a masterful job depicting the thoughts and emotions of someone with sexual addiction. You watch as the pathway of sex addiction as it goes from exciting, bad, to worse. Despite the outward appearance of success and someone who is very well put together, the protagonist Brandon is seen as someone who is empty, frustrated, and haunted by demons from his past. He seems to be tormented on the constant search for his next “high” but does not ever find fulfillment. His sister Sissy also has mental health issues with a long history of self-harm and unstable relationships. There is this implicit scene that suggest some inappropriate relationship between brother and sister though Brandon seems adamantly opposed to any strange physical advances from his sister. It also depicts the inability to have a meaningful relationship with his co-worker due to his sex addiction.",
                "learn": "This movie shows the play-by-play signs that show that sex has become something that is controlling you instead of you controlling sex. The psychological process of addiction is the re-wiring of the brain for the constant need of sex. The brain is biologically wired to look for reproductive opportunities to pass on one’s genetics. So when there is an attractive person, the brain is unconsciously wanting to procreate with any novel person. The person then becomes addicted to novel sexual experiences and the need for instant gratification. This is where the seeking out for new behaviors like one-night-stands with strangers, paying for prostitutes, more “hard-core” pornography, and even homosexual encounters occur. Similar to a high from cocaine, the brain continues to seek out more and therefore the appeal for meaningful, long-term relationships are experienced as “boring.” A healthy relationship with sex is within the context of a loving and committed relationship where sex can deepen intimacy that is supported by emotional intimacy. At some point, a person must come to a decision to want relationships that are real over relationships that feel real in the short moment but really leaves one feeling empty. If you are aware of similar thought processes and behaviors, then treatment is highly recommended. The hope is that there is an increase awareness to the signs of addiction and to seek help in breaking the cycle. If anything, this is a cautionary tale of what happens when the sexual pursuits go too far.",
                "warning": "If nudity and long scenes of different sexual encounters is offensive to you, this is not your movie. The movie is rated NC-17 appropriately because of the many adult encounters such as implied homosexual sex, a threesome with two prostitutes, a shower scene, webcam nudity, and other sexual content. There is also a graphic scene of attempted suicide with plenty of blood. These scenes could trigger someone undergoing sexual addiction as well as someone with suicidal thoughts though it does not inaccurately glorify either. If you have any questions or concerns, please discuss the selection of this movie with your counselor.",
                "image": "https://i.imgur.com/dFlRLar.jpg",
                "levelOne": "true"
            },
        ])
    })
    .then(function (movies) {
        // console.log(movies);
        process.exit();
    })